#!/bin/sh
echo Running libtoolize...
libtoolize -c -f
echo Running aclocal...
aclocal
echo Running autoheader...
autoheader
echo Running automake...
automake -a -c --foreign
echo Running autoconf...
autoconf
